### ISSUE TITLE
Add support for <script> "integrity" and "crossorigin" attributes

### ISSUE THREAD

**Issue by plroebuck** [rstudio/htmltools#101]
In use of htmltools::htmlDependency() for CDNs, it would allow for SRI checking (which ensures resources hosted on third-party servers have not been tampered with), considered a best practice.

Example from jQuery:
```html
<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
```

References:
* [SRI](https://www.srihash.org/)
* [Browser support](https://caniuse.com/#feat=subresource-integrity)
* [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

**Comment by matthewstrasiotto** [comment]
Seconded, SRI's & crossorigins are best practice for ensuring integrity of scripts, & helping prevent bad actors from tampering w/ your scripts. 

Sad to see this hasn't been addressed in 2 years.
