### ISSUE TITLE
Typo in htmltools::HTML error message 

### ISSUE THREAD

**Issue by lusava** [rstudio/htmltools#118]
Hello, not a real issue but just to let you know that there is a typo in an error message of the `HTML` function ("argumemt" instead of "argument").
```
> htmltools::HTML(data.frame())
Error in FUN(X[[i]], ...) : argumemt is not a character vector
```
Best,
Julien

**Comment by yihui** [comment]
Not reproducible to me:

```r
> htmltools::HTML(data.frame())
Error in FUN(X[[i]], ...) : argument is not a character vector

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1
```

The error message comes from `enc2utf8()` in base R, so please make sure [your version of R is up-to-date](https://yihui.name/en/2017/05/when-in-doubt-upgrade/).
