### ISSUE TITLE
3rd Level tag nesting does not render as HTML

### ISSUE THREAD

**Issue by yogat3ch** [rstudio/htmltools#119]
Hi htmltools devs,
I have some puzzling results from nesting tags and knitting these nested tags. Your expert feedback will be appreciated.

I am trying to nest some tables within bootstrap columns using purrr::walk in order to display them nicely. However, I'm finding that third level nesting of tags results in the tags being display as R output rather than tags. Here's the simplest possible example of what I am referring to (the data will be relevant in a moment):

<pre><code>
rs <- list(c(0, -0.058025885318566, 0.377964473009227, -0.0808452083454443, NA, NA, 0, -0.0666666666666667, -0.132453235706504, 0.333333333333333, -0.0808452083454443, 0.132453235706504),                          
c(0.366899692852671, 0.0316069770620507, 0.251629955979423, -0.0146789237925026, NA, NA, 0.104828483672192, -0.302613766334401, 0.168345124585359, 0.0605227532668802, -0.0146789237925026, -0.168345124585359),
c(-0.104828483672192, -0.0316069770620507, 0.205879054892255, 0.308257399642554, NA, NA, -0.104828483672192, 0.0605227532668802, -0.168345124585359, 0.423659272868162, -0.278899552057549, 0.168345124585359),
c(-0.157242725508288, 0.0316069770620507, 0.0228754505435839, 0.5724780279076, NA, NA, -0.157242725508288, -0.0605227532668802, 0.168345124585359, 0.0605227532668802, 0.278899552057549, -0.168345124585359), 
c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
c(0, 0.058025885318566, -0.377964473009227, -0.242535625036333, NA, NA, 0, 0.0666666666666667, 0.132453235706504, -0.333333333333333, 0.404226041727222, -0.132453235706504))
rs <- lapply(rs, function(l){names(l) <- c('MAcceptanceWarmth', 'MDescriptiveLanguage', 'MFollowsLead', 'MMaintainsExtends', 'MHarshCritical', 'MIntrusiveRestrictive', 'DAcceptanceWarmth', 'DDescriptiveLanguage', 'DFollowsLead', 'DMaintainsExtends', 'DHarshCritical', 'DIntrusiveRestrictive')
return(l)})
names(rs) <- c("Positive Feedback", "Sustained Engagement", "Follow Through", "Irritable, Fussy or Crying", "Exhibiting External Distress", "Frozen, Watchful or Withdrawn")

purrr::walk2(.x = rs, .y = names(rs), function(.x, .y){
  
  .x <- as.vector(.x)
 
  .x <- .x[!is.na(.x)]
  print(tags$h4(.y))
  print(
      tags$div(class = "row",tags$div(class = "col-md-6",tags$h5("Positive")), tags$div(class = "col-md-6",tags$h5("Negative")))
    
  )
  })
</code></pre>
This returns the following:
<img src="http://www.yogat3ch.net/yogat3ch/wp-content/uploads/2018/12/ReprexImage1.png" alt="">
Note that the h5 tags at the 3rd level of nesting are not printing as actual HTML tags but rather R output of the HTML.
What I would ideally like to do is generate kableExtra tables inside the bootstrap columns like the below code exhibits. This code runs inline successfully generating the clickable HTML Shiny tags in the Rmarkdown editor, however when I go to knit the document I get a very obtuse error:
<blockquote>Error in if (browse) html_print(x) else print(HTML(as.character(x)), ...) : 
  argument is not interpretable as logical
Calls: <Anonymous> ... <Anonymous> -> pwalk -> do.call -> .f -> print -> print.shiny.tag
In addition: Warning message:
In if (browse) html_print(x) else print(HTML(as.character(x)), ...) :
  the condition has length > 1 and only the first element will be used</blockquote>

<pre><code>
purrr::walk2(.x = rs, .y = names(rs), function(.x, .y){
  nms <- row.names(.x)
  .x <- as.vector(.x)
  names(.x) <- nms
  .x <- .x[!is.na(.x)]
  print(tags$h4(.y))
  print(
      tags$div(class = "row",tags$div(class = "col-md-6",tags$h5("Positive")), tags$div(class = "col-md-6",tags$h5("Negative"))),
      tags$div(class = "row", 
               tags$div(class = "col-md-6", head(.x[order(desc(.x))], 3) %>% as.data.frame %>% kableExtra::kable("html") %>% kableExtra::kable_styling(position = "center")),
               tags$div(class = "col-md-6", tail(.x[order(desc(.x))], 3) %>% as.data.frame %>% kableExtra::kable("html") %>% kableExtra::kable_styling(position = "center"))
               )
  )
  })
  </code></pre>

**Comment by wch** [comment]
Can you provide a full reproducible example -- that is, an .Rmd document?

**Comment by yogat3ch** [comment]
Hi Winston, certainly!
Here is the [Reprex.Rmd](https://drive.google.com/file/d/184DKI1QRyU2hbdinmkZLmDVAu4vIw7BK/view?usp=sharing)
The first chunk demonstrates how the tag nesting results in tags no rendering. If I were to guess, I know that when rendering Rmd documents, any indented HTML tags render as text rather than HTML. I think it might have something to do with the way the knitr engine parses it. Perhaps these tags are being printed with indents and it might be a knitr issue?
The second chunk, another attempt at creating nested tags, causes an error so the chunk is set to eval = F
Thanks for taking a look a this!

**Comment by kcf-jackson** [comment]
Regarding the first chunk, third-level tag has a 4-space indent when printed out. It is interpreted as a block by Rmarkdown, and hence has a \<pre\>-tag wrapped around it. It can be confirmed with this example:

#### untitled.Rmd
```
---
title: "Untitled"
output: 
  html_document
---
<div class="row">
  <div class="col-md-6">
  <h5>Positive</h5>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h5>Positive</h5>
  </div>
</div>
```

I suggest not to rely on `print` when `shiny.tag` objects already work natively with rmarkdown  (and they get printed out properly). Just construct and return the `shiny.tag` object, it would fix the problem.

About the second chunk, you passed two objects to `print`. The second object is treated as optional argument. Calling `print` on each of the objects removes the error.

**Comment by yogat3ch** [comment]
Explained beautifully. Thank you for clarifying this behavior @kcf-jackson!
