### ISSUE TITLE
browsable html lost dependency in print

### ISSUE THREAD

**Issue by haozhu233** [rstudio/htmltools#125]
Hi, I noticed that `print.html` calls `HTML` again in function. This call removes all the HTML dependencies on the original object. 

https://github.com/rstudio/htmltools/blob/4b34e98fc0de2d6f0a1c9ec2b87acce98edbf7a8/R/tags.R#L223-L229

Here is an example. 
```
aaa <- HTML(as.character(shiny::icon("times")))
htmlDependencies(aaa) <- rmarkdown::html_dependency_font_awesome()
browsable(aaa) # which won't print the FA icon

html_print(aaa) # which will print the icon
```

**Comment by haozhu233** [comment]
I'm also willing to submit a PR but I hope someone could let me know whether it would be better to remove this `HTML` call (cuz this is the `print` function for the `html` class already), or you think it would be better to keep it and have some extra step to preserve the html dependency attributes.

**Comment by jcheng5** [comment]
Thanks for the report. I can't think of why we need the HTML() call.
