### ISSUE TITLE
Ignore trailing commas

### ISSUE THREAD

**Issue by hadley** [rstudio/htmltools#128]
``` r
library(htmltools)

div(
  p("one"),
  p("two"),
)
#> Error in tag("div", list(...)): argument is missing, with no default
```

<sup>Created on 2019-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

The easiest way to do this would be to switch from `list()` to `rlang::list2()`

**Comment by jcheng5** [comment]
> The easiest way to do this would be to switch from list() to rlang::list2()

Whaaaaaaaaat!!
