### ISSUE TITLE
Add a script type="module" in renderDependencies 

### ISSUE THREAD

**Issue by battmanux** [rstudio/htmltools#149]
This would be very usefull when creating widgets that depends on mjs files.
Maybe you could test file extention and if it is .mjs, force type="module"

https://github.com/rstudio/htmltools/blob/99a78d033ea50f3f95e25ffd7c0980f832334c8d/R/html_dependency.R#L458

**Comment by slodge** [comment]
This would be very useful - currently we have to wrap our javascript modules in `<script type="module">` blocks in order to load them "by hand"

**Comment by cpsievert** [comment]
This was added to htmltools 0.5.1 via #188

https://github.com/rstudio/htmltools/blob/main/NEWS.md#new-features--improvements-1
