### ISSUE TITLE
includeScript Error in sub: input string 1 is invalid UTF-8

### ISSUE THREAD

**Issue by YsoSirius** [rstudio/htmltools#151]
I am getting the following error when trying to use `includeScript` with a JavaScript file that contains umlauts (ö, ä, etc).

> Warning: Error in sub: input string 1 is invalid UTF-8
>   [No stack trace available]

When I change the function to use an "unknown" encoding it works fine. 

Could we include the encoding argument in `includeScript` and set it to UTF-8 by default, like this?

```
includeScript <- function (path, encoding = "UTF-8", ...) {
  lines <- readLines(path, warn = FALSE, encoding = encoding)
  return(tags$script(HTML(htmltools:::paste8(lines, collapse = "\n")),
                     ...))
}
```

**Comment by trafficonese** [comment]
There is also an issue in shiny https://github.com/rstudio/shiny/issues/2660

**Comment by wch** [comment]
What platform are you using, and have you tried saving the input file with UTF-8 encoding?

**Comment by trafficonese** [comment]
Im on Windows. 
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Yes I tried to save it with encoding, reopen with encoding, but I am always getting the same error.

**Comment by wch** [comment]
Can you provide a reproducible example with attached files?

**Comment by trafficonese** [comment]
Yes, I took the example I posted on shiny#2660

**main.js in /www**
`console.log('Löschen');`

**app.R**
```
library(shiny)
ui <- fluidPage(
  includeScript("www/main.js")
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by wch** [comment]
Can you please attach the files? This is to preserve the exact encoding.

**Comment by trafficonese** [comment]
I apparently did not save it correctly with UTF-8 encoding, I just reopened it with encoding and then saved but didnt "Save with Encoding". 
Anyway, the example is working now. Thank you
