### ISSUE TITLE
Allow tag children to be output inline

### ISSUE THREAD

**Issue by thomasfedb** [rstudio/htmltools#162]
Using this library via Shiny, for example as so:

```
p("This patient is", strong(textOutput("ageYears", inline = T), "years of age"), ".")
```

The output from this leaves a space between "of age" and "." which I've been unable to avoid using any value of `.noWS` so far. Inspecting the resulting HTML suggests that indentation may be to blame.

It would be good to have an `inline` option perhaps?

**Comment by jcheng5** [comment]
You can suppress the space by adding this argument to the call to `strong()`: `.noWS="after"`

The syntax is a little weird, sorry.

**Comment by thomasfedb** [comment]
Using the following:

```
p(strong("This child's BMI is above the 85th percentile."),
  "Drug doses should be based on their",
  strong("85th percentile weight of", textOutput("weight85Rounded", inline = T), "kg", .noWS = "after"), ".")
```

I am still getting a space between "kg" and "." with the following HTML output:

```
<p>
          <strong>This child's BMI is below the 85th percentile.</strong>
          Drug doses should be based on their
          <strong>
            actual weight of
            <span id="weightRounded" class="shiny-text-output shiny-bound-output">23</span>
            kg
          </strong>.
        </p>
```

So the space after the closing `</strong>` is gone but there's still space inside the tag.

**Comment by jcheng5** [comment]
Ah, sure. Try `.noWS=c("before-end", "after")`?

**Comment by thomasfedb** [comment]
That fixes that issue, thanks.

I also have some tags like this:

```
p("They have a zBMI of", textOutput("zbmiRounded", inline = T), ".")
```

In order to pass through the `.noWS` to the underlying call to `span` used a partial application like so:

```
inlineTextOutput <- function(outputId, ...) {
  container = partial(span, ...)
  textOutput(outputId, container)
}
```
