### ISSUE TITLE
path bug in save_html

### ISSUE THREAD

**Issue by kendonB** [rstudio/htmltools#165]
`save_html` sets the wd (https://github.com/rstudio/htmltools/blob/e60e803679eaae7475e18693a0d77b48dda8f908/R/html_print.R#L79) then assumes the file path is still full (https://github.com/rstudio/htmltools/blob/e60e803679eaae7475e18693a0d77b48dda8f908/R/html_print.R#L113)  
``` r
dir.create("subfolder")
htmltools::save_html("htmlcontent", "subfolder/file.html")
#> Warning in base::file(file, open = "w+b"): cannot open file 'subfolder/
#> file.html': No such file or directory
#> Error in base::file(file, open = "w+b"): cannot open the connection
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jcheng5** [comment]
Thanks @kendonB. It looks like adding `file <- basename(file)` under `dir <- dirname(file)` would fix it?

**Comment by cpsievert** [comment]
Pretty sure this was fixed fairly recently
