### ISSUE TITLE
Can we improve the sanity check in validateCssUnit function?

### ISSUE THREAD

**Issue by ShotaOchi** [rstudio/htmltools#167]
validateCssUnit function returns an error message that is hard to understand when running the following code.
```
htmltools::validateCssUnit(character(0))
```
The error message is shown below.
> Error in if (is.null(x) || is.na(x)) return(x) : 
  missing value where TRUE/FALSE needed

This is because ``` is.na(character(0)) ``` returns logical(0).

I think we can improve the sanity check.

For example, modify the lines https://github.com/rstudio/htmltools/blob/984b39c134e111e1518c4e5812110aa531bf803b/R/tags.R#L1362-L1363
like this
```
if (is.null(x))
  return(x)
if( length(x) == 0)
  stop('CSS units must be a single-element numeric or character vector')
if (is.na(x))
  return(x)
```
or
```
if (length(x) == 0)
  return(x)
if (is.na(x))
  return(x)
```
What do you think?

**Comment by jcheng5** [comment]
I think the test should be for `length(x) != 1` rather than `length(x) == 0`, no?

**Comment by ShotaOchi** [comment]
I agree with your opinion.
