### ISSUE TITLE
Error in htmltools while building shiny app

### ISSUE THREAD

**Issue by ashehu1** [rstudio/htmltools#178]
Hi i have encountering this error while trying to build shiny application and i have tried series of ways to resolve it but it seems to be giving me a hard time. i also upgraded the version of R but still having the same error. Any suggestions on how to resolve this please.
Thank you.

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘htmltools’ 0.4.0 is being loaded, but >= 0.4.0.9003 is required

**Comment by jcheng5** [comment]
Some package you’re using requires the development version of htmltools. Install the `remotes` package, then `remotes::install_github("rstudio/htmltools")`. Then restart R.

**Comment by ashehu1** [comment]
Hello,
Thank you for your quick response. The solution worked. thank you.
