### ISSUE TITLE
`HTML` should include linebreaks

### ISSUE THREAD

**Issue by stla** [rstudio/htmltools#182]
Hello,

 I often fell into this trap:

```
HTML(
  "function f(x) {", 
  "  // this is a comment", 
  "  return x+1;",
  "}"
)
# output: function f(x) { // this is a comment   return x+1; }
```
I think `HTML` should add some linebreaks (`\n`) at the end of each argument, when it is used with multiple arguments (like `JS` in `htmlwidgets`). I mean we should get the same as:

```
HTML(
  "function f(x) {\n", 
  "  // this is a comment\n", 
  "  return x+1;\n",
  "}"
)
```
without having to type the `\n`s.

**Comment by wch** [comment]
It's not possible to make this change without breaking a lot of existing code. This change may be convenient for your use case, but there are many who would want it to behave as it currently does.

You could do something like this:


```R
HTML(
"function f(x) {
  // this is a comment
  return x+1;
}"
)
```

Or use `HTML(paste(....., sep = "\n"))`.

**Comment by stla** [comment]
Hi @wch 

  I know how to do :)

One could add an option:

```
HTML <- function(text, ..., .noWS = NULL, breaks = FALSE){
  if(breaks && length(list(...))){
    HTML(paste0(c(text, ...), collapse = "\n"), .noWS = .noWS, breaks = FALSE)
  }else{
    HTML(text, ..., .noWS = .noWS, breaks = FALSE)
  }
}
```
