### ISSUE TITLE
Wrong path in `htmlDependency` consumes the `/tmp` directory

### ISSUE THREAD

**Issue by stla** [rstudio/htmltools#184]
Hello,

 Not sure whether this is a `htmltools` issue or a `DT` issue (@yihui ?).

I did:

```
dep <- htmltools::htmlDependency(
  "yadcf", "0.9.4",
  src = normalizePath("."),
  script = "jquery.dataTables.yadcf.js"
)
```

But this was a mistake, the current directory was not the good one: it didn't contain the file `jquery.dataTables.yadcf.js`. 

Then I attached this dependency to a `DT::datatable` named `dtable`. And when I typed and ran `dtable` in the R console, the R session has been busy during one minute, until I got a warning from R and Ubuntu telling me that my `/tmp` folder had 0 octet left.

**Comment by cpsievert** [comment]
This is likely because, at the time you created this dependency, you had lots of files under your `"."` directory. If you just want to include/mount the `jquery.dataTables.yadcf.js` file, then you should set `all_files = FALSE`

**Comment by stla** [comment]
Thank you. I didn't know this option.
