### ISSUE TITLE
Need some way of not printing whitespace

### ISSUE THREAD

**Issue by wch** [rstudio/htmltools#19]
For example:

``` R
> div("foo", "bar")
<div>
  foo
  bar
</div> 
```

It would be good to be able to do something like one of the following:

``` R
div(.nospace = TRUE, "foo", "bar")
div("foo", nospace(), "bar")
nospace(div("foo", "bar"))
```

**Comment by kevinushey** [comment]
I bumped into this with code of the form `with(tags, pre(code(...)))`, as the injected whitespace will screw up the display of the first line.

**Comment by wch** [comment]
One thing to think about: if we want to be really correct, we'd have to also eliminate whitespace when a div has `display:inline;`. For example, these should look the same, with no space between A and B:

```html
<span>A</span><span>B</span>
```

```html
<div style="display:inline;">A</div><div style="display:inline;">B</div>
```

But unfortunately it's not possible to catch these cases in general because `display` is often set through a CSS file or dynamically from JavaScript.

To take a step back: I think we're adding whitespace is because it makes the HTML more readable. As discussed this issue, we've assumed that adding whitespace has no visible effect for block elements, but it does have a visible effect for inline elements; therefore, it's OK to add whitespace for block elements, but not for inline elements. But we can't tell with 100% reliability whether an element is block vs. inline just based on the tag type, because the `display` property can be changed.

I'm not sure if this changes what we'll do, but it's worth keeping in mind.

**Comment by jcheng5** [comment]
FWIW, haml handles this by letting you specify the whitespace behavior. http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_removal__and_

If we did something like this we could actually leave the default behavior alone, which would be so great from a backwards compatibility perspective.

**Comment by sbliven** [comment]
There might be a better way of doing this, but I ran into this problem when I tried to use `htmlTemplate` as a generic templating library. In my case I was trying to generate some javascript blocks. A simplified example might be

```r
htmlTemplate(text_="var a = \"{{toupper(a)}}\";", a="hello")
```
Output:
```
var a = "
HELLO
";
```
In this case the extra whitespace is completely ruining my intended purpose. I realize this diverges somewhat from the intended use of htmlTemplate, but I'd rather not include a separate template package just for this.

Adding a parameter to htmlTemplate to disable the added newlines would be great.

**Comment by wch** [comment]
Relevant: https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33

**Comment by sanjmeh** [comment]
It is now a year since the last activity on this issue. The whitespace on inline HTML tags is still appearing and this makes the `tag$` functions less useful. In my case, I have to scrap an entire code section as a bug was traced to a white space in the HTML that was forcibly injected by `tag$` used in a shinyapp. Is there any solution within R apart from the `haml` mentioned above by @jcheng5?

**Comment by jcubic** [comment]
There is still issue with `{{ ?? }}`, is this separated issue?

**Comment by wch** [comment]
@jcubic Do you mind filing a new issue about that?
