### ISSUE TITLE
Using htmlDependency for HTML imports

### ISSUE THREAD

**Issue by daattali** [rstudio/htmltools#210]
HTMl imports can be thought of as similar to javascript-type resources, they're declared with `<link rel="import" href="test.html">`

Disclaimer: [HTML imports are an obsolete HTML feature](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports) so new code will not use it, and old code **should** migrate away

I'm trying to write a package that wraps around a web components that uses HTML imports. I'm able to use it when declaring the `<link>` tag directly in the UI, but because this is more like a dependency, I wanted to use `htmlDependency()` for it.

In its current form, I couldn't find a way for `htmlDependency()` to allow me to use HTML imports. Since the `script` argument can use a named list and since the `stylesheet` argument creates a `<link>` tag, I tried using `htmlDependency(stylesheet = c(rel="import", href="test.html"))` but that doesn't seem to work. This results in two `<link>` tags in the document. 

Is there a way to use HTML imports currently? If not, will this be something to consider? A negative answer is totally reasonable too since it's not the future of the web.

**Comment by cpsievert** [comment]
I suppose we could consider supporting something like `htmlDependency(stylesheet = list(foo="bar", href="test.html"))` in a similar way to how to can now provide `list()`s to `script` (see https://github.com/rstudio/htmltools/pull/188 and https://github.com/rstudio/shiny/pull/3395), but we'll need a better motivation than to support an obsolete feature.

**Comment by daattali** [comment]
I can't think of another reason. If the two PRs you linked to already paved the path for this and it's trivial to add support for another more attribute then I'd vote for supporting it. If it's not very easy, then spending a lot of resources on an obsolete feature as you say is porbably not worth it.

**Comment by cpsievert** [comment]
Closing in favor of #272 since that more succinctly explains the issue
