### ISSUE TITLE
Consider having tagQuery()'s modifying methods return invisible()

### ISSUE THREAD

**Issue by cpsievert** [rstudio/htmltools#219]
I find it a little surprising this prints twice

```r
x <- div(a(), span(), a())
xq <- tagQuery(x)
xq$addClass("foo")
xq
```

**Comment by cpsievert** [comment]
By hiding the result, I think is a bit more clear that you're modifying `xq`

**Comment by schloerke** [comment]
I had originally approached it to be similar to plumber where the router should always be printed (never invisible). 

But since it is not pipe methods, this seems fair.
