### ISSUE TITLE
Consider renaming `$asTags(selected = TRUE)` 

### ISSUE THREAD

**Issue by wch** [rstudio/htmltools#221]
It's a bit strange that:
* To get the whole tagQuery object back as a tag object, you call `$asTags(selected=FALSE)`.
* To get just the selected elements as tag objects, you call `$asTags(selected=TRUE)`.

The naming is a bit counterintuitive.

Maybe we should use:
* `$asTags()`
* `$selectedAsTags()` or `$asTagsSelected()`

Or possibly:
* `$asTags(all = TRUE)` (this would be the default)
* `$asTags(all = FALSE)`

**Comment by cpsievert** [comment]
Now that I'm writing about this, I almost want to get rid of `$asTags()` and instead have a `$root()` and `$selected()` them both return tags, does that seem reasonable @schloerke?

**Comment by cpsievert** [comment]
(Also, maybe it makes sense to do this as a part of https://github.com/rstudio/htmltools/issues/213)

**Comment by schloerke** [comment]
Two issues with one PR. I'm for it!
