### ISSUE TITLE
Remove `$rebuild()` as a public tagQuery method

### ISSUE THREAD

**Issue by cpsievert** [rstudio/htmltools#231]
Since we can use `tagQuery(x)` instead as a way to "rebuild"

And also remove `$print()`?

**Comment by schloerke** [comment]
I believe `$print()` can be removed if https://github.com/rstudio/htmltools/pull/230 is merged. 

With `$rebuild()`, https://github.com/rstudio/htmltools/pull/235 is removing a LOT of calls to `$rebuild()`. So it might be good to keep it? A workaround would to call `$each(list)` which will internally call `rebuild_()` after walking the selected elements.

**Comment by cpsievert** [comment]
> So it might be good to keep it?

Perhaps? Let's only ship it though if we can manage to think of a real situation where one might need it, and document that.

**Comment by schloerke** [comment]
Let's remove it for now. And add it in later if there is a common use case.

Workaround for now:

```r
tagQ$each(force)
```
