### ISSUE TITLE
Pass tags instead of tag envs through `tagQuery()$filter()`

### ISSUE THREAD

**Issue by cpsievert** [rstudio/htmltools#232]
To help prevent the possibility of someone modifying the root when they just want to the filter down the subset

**Comment by cpsievert** [comment]
We should also consider doing this for `$each()` and any other method that provides access to tag envs since it'll feel slightly more natural to keep functions "pure"

**Comment by wch** [comment]
I think that users should just provide a filter function that doesn't modify the tag env.

Here's my reasoning: `$each()` should work on tag-envs -- it seems like a legitimate use case to modify the objects in place. And with `$filter()`, it should provide the same interface, where it calls the function with a tag-env. Also, the conversion back and forth would have a performance penalty, especially if there's a large tree (I assume that the conversion would be recursive).

That said, it might be a good idea to provide users with a way to convert their tag-env objects to a regular tag object, if they want to do use a filter function that could modify the tag, but don't want to actually modify it. So perhaps we should export `tagEnvToTags()`, and possibly give it a shorter/simpler name.

**Comment by cpsievert** [comment]
> it might be a good idea to provide users with a way to convert their tag-env objects to a regular tag object

I agree. I was thinking that'd be useful to provide that via `as.tags.htmltools.tag.query()`, but I think @schloerke may have good reasons to not do that?

**Comment by schloerke** [comment]
`as.tags()` is a "this layer of tags may be treated as tags" and should not convert children to tags method. (I believe the name `as.tags()` is misleading.)
`tagEnvToTags()` does a complete tree conversion.

If trying to convert a tag env into a standard tag, I'd argue that `tagQuery(myTagEnv)$selected()` should be used instead. This makes `tagQuery()` the function to convert tags to tag envs and tag envs back to tags.

---------------------

That being said, this seems annoying...
```r
tagQ$filter(function(el, i) {
	dangerousFilter(tagQuery(el)$selected()[[1]])
})
```

**Comment by schloerke** [comment]
There is also the danger that you send in a tag env and a UI method is not safe. This method could alter the tag env when called, altering the original object in place. 

To deter this behavior, tagEnvs should not be allowed within the UI at all
