### ISSUE TITLE
Should we rename `tagAddRenderHook()` to `tagAppendRenderHook()`

### ISSUE THREAD

**Issue by schloerke** [rstudio/htmltools#248]
This would help with autocomplete and mix with functions like:

```r
tagAppendAttributes()
tagAppendChild()
tagAppendChildren()
```

Currently, there are no other `tagAdd*()` methods.

cc @cpsievert

**Comment by wch** [comment]
I don't think so, since the render hook data structure isn't exposed, and appending seems strange.

**Comment by cpsievert** [comment]
I think this ship has sailed
