### ISSUE TITLE
Add `.cssSelector` to methods like `tagAppendChildren(..., .cssSelector = NULL)`

### ISSUE THREAD

**Issue by schloerke** [rstudio/htmltools#251]
If the `.cssSelector` is not `NULL`, call `tagQuery(tag)$find(.cssSelector)$append(...)$allTags()`.

Do this for other method like `tagAppendChildren()`.

This gives more motivation to export `tagInsertChildren()` (#225)

**Comment by wch** [comment]
We'll need to make sure that users are aware that if they do this, it goes through `tagQuery()`, and is subject to whatever changes `tagQuery` will make to the object. For example, lists and tagLists will be flattened when this happens. I don't know offhand what other changes `tagQuery()` will make, but we should make sure they're all documented.

**Comment by schloerke** [comment]
Should just be the flattening of `TAG$children` into a single list

**Comment by schloerke** [comment]
Internal tag name ordering is fixed in #249
