### ISSUE TITLE
Bad behavior when passing `as.tags` output to `shiny::renderUI`

### ISSUE THREAD

**Issue by garrettgman** [rstudio/htmltools#26]
When I render this file, an extra "div form-group shiny-input-container" appears in front of the label of the second slider. This seems to be a side effect of `as.tags` not passing on the class `shiny.tag`

The included `as.tags.shiny.tag` functions seems to fix it, but the function is a bit of a hack.

This comes up in real life when I eval and parse code from a shinyAce editor then feed it into `as.tags`

```
    ---
    runtime: shiny
    ---

    ```{r}
    # Works fine
    renderUI({
      sliderInput("s1", "Slide Me", min = 0, max = 10, val = 5)
    })

    # Odd label
    renderUI({
      htmltools::as.tags(sliderInput("s1", "Slide Me", min = 0, max = 10, val = 5))
    })
    ```

    ```{r eval = FALSE}
    # eval = FALSE
    # But works again
    as.tags.shiny.tag <- function(...) {
      structure(htmltools:::as.tags.default(...), class = "shiny.tag")
    }

    renderUI({
      htmltools::as.tags(sliderInput("s1", "Slide Me", min = 0, max = 10, val = 5))
    })
    ```

```

**Comment by yihui** [comment]
I realized I'd need this as well, so I added the S3 methods in #29.
