### ISSUE TITLE
`tagAppendAttributes()` no longer changes order of attributes

### ISSUE THREAD

**Issue by wch** [rstudio/htmltools#281]
Prior to #212, `tagAppendAttributes()` would cause attributes to change order if the added attribute was one that already was present:

```R
tagAppendAttributes(
  div(b = "b", a = "a"),
  b = "b2"
)
#> <div a="a" b="b b2"></div>
```

After #212, the original order is preserved:

```R
tagAppendAttributes(
  div(b = "b", a = "a"),
  b = "b2"
)
#> <div b="b b2" a="a"></div>
```

This is probably an improvement in the behavior, but it is causing some test failures in downstream packages, for example, https://github.com/rstudio/shiny/runs/3081538775?check_suite_focus=true#step:17:141

One odd thing is that the PR caused behavior for that test to change in R 3.6 and 4.0, but **not** in R 3.4 or 3.5. (I don't know if the same R version difference is true for the minimal test I have above.)

One way to go is to add unit tests in this package that enforce the new behavior. We would also have to be mindful about possible test failures in other downstream packages.

The other way to go is to revert to the old behavior, and also add tests that enforce the behavior.

**Comment by cpsievert** [comment]
> One odd thing is that the PR caused behavior for that test to change in R 3.6 and 4.0, but not in R 3.4 or 3.5. (I don't know if the same R version difference is true for the minimal test I have above.)

I don't think that's right -- we skip those unit tests on R < 3.6 because of the change in the default RNGkind()  (tabPanel ids are random), which would explain why the test isn’t failing https://github.com/rstudio/shiny/blob/aba6b2/tests/testthat/test-tabPanel.R#L17-L22 

I'm fairly sure this difference can be explained by this change to `flattenTagAttribs()` https://github.com/rstudio/htmltools/pull/212/files#diff-e5931dd5e8497a88ace9ea091ba55668ce625594355741564fb640c4c97c638aR1327-R1335

@schloerke should we just revert that change or should we try to keep it?

**Comment by schloerke** [comment]
Correct. 

I'm up for either. But currently it will produce inconsistent results depending on the attribs size.

Maybe we could add in a `sort()` call. This should fix it. I'll see where to the break point will change to.

**Comment by schloerke** [comment]
Reprex:

```r
z <- div(); 
while (length(unique(names(z$attribs))) < 46) {  
  args <- list(tag = z); 
  args[[sample(c(letters, LETTERS), 1)]] <- "a"; 
  z <- do.call(tagAppendAttributes, args); 
  if (length(unique(names(z$attribs))) > 44) { 
    cat("\n"); 
    print(length(unique(names(z$attribs)))); 
    print(z) 
  }
}
```

The output will switch order once the length is 46.

```
[1] 45
<div w="a a a a a" d="a" y="a" c="a a a a" A="a" g="a a a a" F="a" s="a a" r="a a" u="a" Z="a a a" N="a" T="a a" o="a" b="a" h="a" R="a a a" W="a a" a="a a" G="a" f="a a" v="a" L="a" Y="a a" O="a" j="a" H="a" U="a a" B="a" M="a a" C="a" i="a" D="a a" J="a a" t="a" n="a" e="a" K="a" V="a" l="a" p="a" m="a a" k="a" S="a a" X="a"></div>

[1] 46
<div a="a a" A="a" b="a" B="a" c="a a a a" C="a" d="a" D="a a" e="a" f="a a" F="a" g="a a a a" G="a" h="a" H="a" i="a" j="a" J="a a" k="a" K="a" l="a" L="a" m="a a" M="a a" n="a" N="a" o="a" O="a" p="a" r="a a" R="a a a" s="a a" S="a a" t="a" T="a a" u="a" U="a a" v="a" V="a" w="a a a a a" W="a a" X="a" y="a" Y="a a" z="a" Z="a a a"></div>
```
