### ISSUE TITLE
body style has default padding: 40px, unclear how to change this value

### ISSUE THREAD

**Issue by bbt-dev** [rstudio/htmltools#297]
This is not a bug, but an undocumented aspect that I would like to ask about.
By default, the html document created by the htmlwidgets::saveWidget which use htmltools (for example, `htmlwidgets::saveWidget (reactable(iris))`) has the following attributes in the body tag: `<body class="vsc-initialized" style='margin: 9px; padding: 40px; ">` that leads to excessive padding from the top of the page.
I have tried to find any documentation how to change the "style='padding: 40px;'" but there is no documentation, and in the code of the [save_html function](https://github.com/rstudio/htmltools/blob/main/R/html_print.R) no styles are defined.
Please could you suggest how it is possible to change the style of the body tag and adjust the "padding: 40px" to the desired level?

**Comment by cpsievert** [comment]
I'm pretty sure the "correct" way to specify this padding is via `htmlwidgets::sizingPolicy(browser.padding = ...)`

**Comment by bbt-dev** [comment]
Thanks a lot, this works! 
Its a little bit strange that htmlwidgets::saveWidget could not accept an argument htmlwidgets::sizingPolicy(padding = 0), and the final solution is the following:
```
object2save <- reactable(iris)
object2save$sizingPolicy$padding <- 4
htmlwidgets::saveWidget(object2save, file = "example.html", 
			selfcontained = FALSE, libdir = "lib")
```
