### ISSUE TITLE
Critical Error: includeMarkdown() fails if the file is empty

### ISSUE THREAD

**Issue by VermillionAzure** [rstudio/htmltools#30]
![htmltools_error](https://cloud.githubusercontent.com/assets/844699/9052858/6993913e-3a08-11e5-917c-926a41c47be0.png)

I've been developing a module, and I've just noticed that the `includeMarkdown()` function will fail if the file is empty. Although this may seem fairly harmless, I have a project in which we develop modules that may include a help file, and the example `help.md` file is sometimes empty. If I add just a small amount of text to it, the function works again, and if I remove all text, the function fails.

It'd be nice just to include an empty pair of tags just to make sure that the function stays in tact in this very mundane fail case.

**Comment by yihui** [comment]
Thanks for the report! It has been fixed in the development version of the markdown package: https://github.com/rstudio/markdown
