### ISSUE TITLE
`head()` does not render under `html()`

### ISSUE THREAD

**Issue by mpettis** [rstudio/htmltools#322]
`version 0.5.2.9000`
From example at: https://rstudio.github.io/htmltools/reference/builder.html#examples

No need for reprex -- the example there puts a head with a title in the list structure:
```r
tags$html(
  tags$head(
    tags$title('My first page')
  ),
  tags$body(
    h1('My first heading'),
```

but it is not rendered, as shown in the output in at the same link:

```r
#> <html>
#>   <body>
#>     <h1>My first heading</h1>
```

I confirmed that that is indeed the case with other ways of trying it.

**Comment by mpettis** [comment]
I am hoping to use `{htmltools}` as a standalone for a mini-webserver in conjunction with `{plumber}`, and I am not sure how to render the created structure back for plumber to serve it.  Your example uses `shiny:::renderPage()`, but that adds a lot of header information that seems specific to `{shiny}`, which I'm not using.  What is the way to create a html document with htmltools and then return the html that can be streamed back in the request (like in plumber?).  The following is close, but again, the header is separated from the rest, and the `html` section has only the body rendered under it.  Now, I can hack it to take this structure and stick the header right after the opening `html` tag, but I suspect I am missing something more elegant.

``` r
library(htmltools)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
withTags(
    html(
        head(
            title("First Page")
        ),
        body(
            h1("First Heading")
        )
    )
) %>% renderTags()
#> $head
#>   <title>First Page</title>
#> 
#> $singletons
#> character(0)
#> 
#> $dependencies
#> list()
#> 
#> $html
#> <html>
#>   <body>
#>     <h1>First Heading</h1>
#>   </body>
#> </html>
```

<sup>Created on 2022-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mpettis** [comment]
Never mind... answered my own question:

``` r
library(htmltools)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
withTags(
    html(
        head(
            title("First Page")
        ),
        body(
            h1("First Heading")
        )
    )
) %>% doRenderTags()
```

<html>
  <head>
    <title>First Page</title>
  </head>
  <body>
    <h1>First Heading</h1>
  </body>
</html>

<sup>Created on 2022-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cpsievert** [comment]
> What is the way to create a html document with htmltools and then return the html that can be streamed back in the request (like in plumber?).

I think the "official" way would be to use `save_html()`, but that requires writing (and probably reading?) from disk. If you wan't to avoid I/O, `renderTags()` is probably the best abstraction we have right now, but you'll need to think more carefully about how to handle `HTMLDependency()`s (i.e., `renderDependencies()` in the head and `copyDependencyToDir()`) with that approach.

Either way, you'll have to somehow make the `HTMLDependency()` files available through a `{plumber}` route/mount (so that the resulting HTML can make requests to external JS/CSS files)

**Comment by wch** [comment]
Oh, actually, with `save_html()`, you could use `stdout()`:

```R
save_html(x, stdout())
```

**Comment by mpettis** [comment]
@wch @cpsievert I think the `doRenderTags()` call, in my last comment above, does what I want, and sticks to what I explicitly constructed, and I've been running with that.  Unless I'm missing something.  But thanks!
