### ISSUE TITLE
Need to restrict the fastmap version

### ISSUE THREAD

**Issue by colearendt** [rstudio/htmltools#330]
`fastmap` < 1.1.0 did not have a `faststack` function, which `htmltools` depends on. This creates an installation error in some environments (particularly upgrades):

```
object ‘faststack’ is not exported by 'namespace:fastmap'
```

As a result, we should pin `fastmap (>= 1.1.0)` in the DESCRIPTION file or relax the need for `faststack`

https://github.com/r-lib/fastmap/blob/main/NEWS.md

`shiny` pins to >= htmltools 0.5.2, so this issue will probably hit in other places as well

https://github.com/rstudio/shiny/blob/54e5a6b43c4d2d4e24e571e71a9773be046531b7/DESCRIPTION#L82

**Comment by hadley** [comment]
See #324 and before that #291

@cpsievert since this is hitting multiple people, maybe it's time for a htmltools release?

**Comment by cpsievert** [comment]
Just hit cran this morning
