### ISSUE TITLE
htmlTemplate not respecting indentation

### ISSUE THREAD

**Issue by ramnathv** [rstudio/htmltools#57]
Consider the following example.

``` r
library(htmltools)
template <- "
<div>
  <span>Hello</span>
  <span>{{ user }}</span>
</div>
"
htmlTemplate(text_ = template, user = 'Jane Doe')
```

It renders as shown below

``` html
<div>
  <span>Hello</span>
  <span>
Jane Doe
</span>
</div>
```

I would have expected `htmlTemplate` to respect the indentation and instead render

``` html
<div>
  <span>Hello</span>
  <span>Jane Doe</span>
</div>
```

**Comment by wch** [comment]
Hm, that was a design choice to add whitespace around the returned values from R code blocks, although I can see why you'd want it to not do that. Now that I think about it, I'm not sure why we decided to add whitespace, since it doesn't seem advantageous in any situations I can think of.

**Comment by wch** [comment]
Now that I look at the code again, it's a little more clear why: it returns a `tagList` where the pieces alternate between raw HTML and the returned values from the code blocks. For example:

```R
> user <- "Jane Doe"
> template <- "<span>{{ user }}</span>"
> str(htmlTemplate(text_ = template, user = 'Jane Doe'))
List of 1
 $ :List of 3
  ..$ <span> :Classes 'html', 'character'  atomic [1:1] <span>
  .. .. ..- attr(*, "html")= logi TRUE
  ..$  user  : chr "Jane Doe"
  ..$ </span>:Classes 'html', 'character'  atomic [1:1] </span>
  .. .. ..- attr(*, "html")= logi TRUE
 - attr(*, "class")= chr [1:2] "shiny.tag.list" "list"
```

So the rendering behavior for tagLists would need to be changed.

**Comment by jcheng5** [comment]
When we revisit the excess-whitespace issue in general I bet a nice fix for this issue will fall out as well. I think we will need the ability for tag objects to "eat" the whitespace to either side, we can have all the `HTML()` blocks in this case eat both sides.
