### ISSUE TITLE
Error when an attribute is character(0)

### ISSUE THREAD

**Issue by wch** [rstudio/htmltools#65]
For example:

```R
div(foo=character(0), "text")
# Error in if (!is.na(attribValue)) { : argument is of length zero
```

I think it should just drop the attribute, the same as if it were `NULL`.

**Comment by yihui** [comment]
I feel this might be handy syntax for attributes that do not need to take values, e.g.

```html
<option value="..." selected>...</option>
```

Currently htmltools can only generate this

```html
<option value="..." selected="selected">...</option>
```

**Comment by jcheng5** [comment]
@wch +1

@yihui That's already supported, pass `selected = NA`
