### ISSUE TITLE
head tag broken?

### ISSUE THREAD

**Issue by cbailiss** [rstudio/htmltools#77]
I am having trouble getting the html head tag to be emitted.  Other tags seem to work.  Example:

```
> htmltools::tags$body()
<body></body>
> htmltools::tags$head()

> htmltools::tags$title('Test')
<title>Test</title>
> htmltools::tags$head(htmltools::tags$title('Test'))

> 
```

i.e. htmltools::tags$head() emits nothing.  Am I doing something wrong?  Or is this broken?

I am using the current version of the htmltools package from CRAN, i.e. 0.3.5

**Comment by wch** [comment]
The `print` method (`print.shiny.tags`) doesn't print out the head content, because it does special processing on it. For example, if you put `tags$head()` inside some body content, the head content will get hoisted to the head section of the document.

For example:

```R
library(htmltools)

# Render html tag object to a complete html file, then print it
display_html_file <- function(x) {
  file <- tempfile()
  save_html(x, file)
  cat(readLines(file), sep = "\n")
  rm(file)
}


x <- tags$head(tags$title('Test'))
display_html_file(x)
# <!DOCTYPE html>
# <html>
# <head>
# <meta charset="utf-8"/>
#   
#   <title>Test</title>
# </head>
# <body style="background-color:white;">
# 
# </body>
# </html>
  
  
x <- div(
  "text content",
  tags$head(tags$title('Test')),
  "more content",
  tags$head(tags$script('// script content'))
)
display_html_file(x)
# <!DOCTYPE html>
# <html>
# <head>
# <meta charset="utf-8"/>
# 
#   <title>Test</title>
#   <script>// script content</script>
# </head>
# <body style="background-color:white;">
# <div>
#   text content
# more content
# </div>
# </body>
# </html>

```

**Comment by cbailiss** [comment]
Thank you @wch for the quick response and detailed examples.  That does make some sense, however, there are use cases where it would be useful to not have this special processing happen.  Could it be disabled, e.g. via a parameter?

Also, please allow me to explain where some confusion arose from.  At the bottom of page 4 in the htmltools package reference manual PDF, is the following example:

```
library(htmltools)
doc <- tags$html(
  tags$head(tags$title('My first page')),
  tags$body(
    h1('My first heading'),
    p('My first paragraph, with some ', strong('bold'), ' text.'),
    div(id='myDiv', class='simpleDiv', 'Here is a div with some attributes.')
  )
)
cat(as.character(doc))
```

This example suggests that a head tag should be output (otherwise why include it in the example).   However this example only outputs the following to the console:

```
<html>
  <body>
    <h1>My first heading</h1>
    <p>
      My first paragraph, with some 
      <strong>bold</strong>
       text.
    </p>
    <div id="myDiv" class="simpleDiv">Here is a div with some attributes.</div>
  </body>
</html>
```

Clearly, there is no head tag here.  I would suggest either changing the example or at least explaining why the head tag is not emitted.  At present, it appears like a bug.

**Comment by cbailiss** [comment]
For my use case, I was constructing some HTML in line with the example, where the special processing does not happen.  It would be useful to know which functions implement this logic to emit the head element.  From your examples, it appears save_html() does.  Is this the only function?
Having to save to file and read from file feels a bit awkward if an in-memory HTML string is being constructed.

**Comment by dcomtois** [comment]
I've been struggling with this as well. I would expect this to work...
```
doc <- tags$html(
  tags$head(
    tags$meta(charset="utf-8"),
    tags$title("My Title")
  ),
  tags$body(
    tags$div(class="container",
             h2("Section title"),
             p("A paragraph")
    )
  )
)
```
As a workaround, I've used `tags$header` instead, and then `gsub`'ed </?header> with </?head>.  :\
