### ISSUE TITLE
<html>after <!DOCTYPE html> tag should use lang="en" property/attribute

### ISSUE THREAD

**Issue by dmpe** [rstudio/htmltools#82]
https://github.com/rstudio/htmltools/blob/master/R/html_print.R#L89
and please make it customizable e.g. lang="cs", lang="de", lang="lu" so that `shiny` can take advantage of it. 

BIG THANKS

**Comment by psalmody** [comment]
This is a [WCAG 2.0 requirement issue](https://www.w3.org/TR/WCAG20-TECHS/H57.html)
