### ISSUE TITLE
add md() convenience function to write fragments in markdown

### ISSUE THREAD

**Issue by maxheld83** [rstudio/htmltools#94]
this has been migrated from https://github.com/rstudio/shiny/issues/1936.

I'll do a PR sometime soon, as suggested by @jcheng5.

----

I'm so used to writing in basic markdown (*emph*, **bold**, `pre` etc.), I can't get myself to write, say `shiny::tags$em("foo")`.
Maybe others are feeling the same.

I build myself a simple wrapper to be able to easily write markdown:

```
#' @title Convert markdown to html
#'
#' @param text A character vector to be converted to markdown.
#'
#' @param HTML A logical flag, indicating whether the result should additionally be wrapped in shiny::HTML().
#'
#' @noRd
md <- function(text, HTML = TRUE) {
  res <- markdown::renderMarkdown(
    file = NULL,
    output = NULL,
    text = text
  )
  if (HTML) {
    res <- shiny::HTML(text = res)
  }
  return(res)
}
```

which can be used wherever shiny expects HTML.

Now I can write something like:

```
fileInput(
  inputId = "rdata",
  label = md("Upload a `*.rdata` file created by *pensieve*."),
)
```
which makes life a little easier.

Is there any interest in supporting this directly in shiny? I'm guessing an `md()` function might be an alternative to / modelled on the existing `HTML()`.

If there's interest, I'd be happy to write up a PR.

---

Just to be sure, what this isn't:
- this is not about including external files, `shiny::includeMarkdown()` does that already,
- this is strictly about *Markdown*, **not** RMarkdown.

**Comment by jjallaire** [comment]
You might consider the [commonmark](https://github.com/jeroen/commonmark) package rather than the markdown package (but I guess it would be best of shiny made the mode to commonmark as well for `includeMarkdown`).

**Comment by cpsievert** [comment]
There's now `shiny::markdown()`, which I think does what you're thinking of (let me know if not)
