### ISSUE TITLE
Error in enc2utf8(text) : argument is not a character vector when rendering DT

### ISSUE THREAD

**Issue by batpigandme** [rstudio/htmltools#97]
When knitting an Rmd with a datatable, was failing with:
`Error in enc2utf8(text) argument is not a character vector`
I tried `include = FALSE` and `echo = FALSE` on the `DT::datatable` chunk, but still could not knit the document.

Based on the traceback (collapsed, below) it looks like it's failing on `htmlEscape(dep$meta)`. 

Possibly related to: https://github.com/rstudio/htmltools/blob/9e219b8db95ca324c58c67e168e15b24da0fa64b/R/html_escape.R#L36

<details>
<summary>Traceback</summary>
9. htmlEscape(dep$meta) 

8. paste("<meta name=\"", htmlEscape(names(dep$meta)), "\" content=\"", 
    htmlEscape(dep$meta), "\" />", sep = "") 

7. renderDependencies(dependencies, "file", encodeFunc = identity, 
    hrefFilter = function(path) {
        html_reference_path(path, lib_dir, output_dir)
    }) 

6. html_dependencies_as_string(dependencies, NULL, NULL) 

5. as_tmpfile(html_dependencies_as_string(dependencies, NULL, NULL)) 

4. pandoc_html_extras_args(extras, self_contained, lib_dir, output_dir) 

3. base(...)

2. output_format$pre_processor(yaml_front_matter, utf8_input, runtime, knit_meta, files_dir, output_dir) 

1. rmarkdown::render(here::here("inst", "pkgreporting.Rmd"))

</details>

I was able to fix this by downgrading to the CRAN version of htmltools.

pandoc version 2.2
rmarkdown at https://github.com/rstudio/markdown/commit/5abbfaec56cabf1b59ee5d72640d83b30dd71172

Just let me know if you need more info, or if this is the wrong repo! 😳

**Comment by batpigandme** [comment]
🎉 It does! Thank you 🙏 !

**Comment by wch** [comment]
The fix for htmltools has been merged into master.
